version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
    command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.14
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_USER: ticketing
      MYSQL_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: ticketing
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/conf/:/etc/mysql/conf.d/
      - ./prisma/migrations/20220225062029_init/:/docker-entrypoint-initdb.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

  server:
    build:
      context: ./
      dockerfile: ./dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:1q2w3e4r5t@mysql:3306/ticketing
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: 1q2w3e4r5t
      SERVICE_PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
